fsck.f2fs: fix to avoid using uninitialized buffer
fsck.c: In function ‘chk_and_fix_wp_with_sit’:
fsck.c:3529:17: error: variable-sized object may not be initialized
 3529 |                 char buffer[F2FS_BLKSIZE] = {};
      |                 ^~~~

The reason is F2FS_BLKSIZE macro is defined w/ c.blksize, let's use
calloc() to allocate zeroed memory to fix this issue.

Cc: Daeho Jeong <daehojeong@google.com>
Signed-off-by: Chao Yu <chao@kernel.org>
Reviewed-by: Daeho Jeong <daehojeong@google.com>
Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>